name: Cpp

on:
  push:
    branches: [main, "v*.x"]
  pull_request:
    branches: [main, "v*.x"]
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  cpp-check-ubuntu-24:
    name: C++ Check @ Ubuntu 24.04
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/workflows/shared_cpp_steps

  cpp-check-ubuntu-22:
    name: C++ Check @ Ubuntu 22.04
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/workflows/shared_cpp_steps

  cpp-check-macos-14:
    name: C++ Check @ macOS 14
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/workflows/shared_cpp_steps

  cpp-check-windows-2022:
    name: C++ Check @ Windows 2022
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/workflows/shared_cpp_steps
